version: '3.8'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: nginx/
    ports:
      - 3000:80
    depends_on:
      - share_portfolio_frontend
    volumes:
      - ./app:/var/www:delegated

  share_portfolio_frontend:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.local
    environment:
      NEXT_PUBLIC_SHARE_PORTFOLIO_API: http://share_portfolio_backend:4000
    command: npm run dev
    stdin_open: true
    tty: true
    restart: always

networks:
  default:
    name: share_portfolio
