enum FetcherKeys {
  GET_OVERVIEW = 'GET_OVERVIEW_KEY',
  LIST_MONTHLY_BALANCES = 'LIST_MONTHLY_BALANCES_KEY',
  LIST_TRANSACTIONS = 'LIST_TRANSACTIONS_KEY',
  LIST_INSTITUTIONS = 'LIST_INSTITUTIONS_KEY',
  GET_TRANSACTION_TABLE_FILTERS = 'GET_TRANSACTION_TABLE_FILTERS_KEY',
}

export default FetcherKeys;
